name: gea
description: GEA

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  location: ^4.1.1
  google_maps_flutter: ^2.0.3
  raw_gnss:
    path: ./pubmod/raw_gnss-1.1.0+1/
  permission_handler: ^10.2.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_analytics: ^10.0.4
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.4
  splashscreen: 1.3.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.2
  flutter_isolate: ^2.0.0
  webview_flutter: any
  google_fonts: ^3.0.1
  charts_flutter: any
  gnss_status: ^1.0.1
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.5
  after_layout: ^1.1.0
  mailto: ^2.0.0
  url_launcher: ^6.0.3
  path_provider: ^2.0.1
  flutter_android: ^0.8.0
  flutter_share: ^2.0.0
  fluttertoast: ^8.0.7
  web_socket_channel: ^2.1.0
  socket_io_client: ^2.0.0
  # arcore_flutter_plugin: ^0.0.11
  device_info: ^2.0.3
  open_file: ^3.2.1
  wakelock: ^0.6.2
  flutter_compass: ^0.7.0
  card_settings: ^3.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/gea_icon.jpeg
    - assets/images/status.png
    - assets/images/gps.png
    - assets/images/beidou.png
    - assets/images/galileo.png
    - assets/images/glonass.png
    - assets/images/log_icon.png
    - assets/images/rt_icon.png
    - assets/logos/github.png
    - assets/logos/google.png
    - assets/images/polar_chart.png
    - assets/images/polar_chart_grey.png
    - assets/images/single_marker.png
    - assets/images/rtk_marker.png
    - assets/images/ppp_marker.png
    - assets/json/night.json
    - assets/json/light.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages